#!/bin/bash
#
# hhvm        Startup script for the HipHop Server
#
# chkconfig: - 85 15
# description: HipHop is a high performance PHP toolchain
# processname: hhvm
# config: /etc/hhvm/server.hdf
# pidfile: /var/run/hhvm/hhvm.pid
#
# based on file from https://github.com/makewhatis/rpm-hiphop-php/blob/master/hhvm.init
#   as well as (to a much lesser degree) some other sources 

### BEGIN INIT INFO
# Provides: hhvm
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start and stop HipHop Server
# Description: HipHop is a high performance PHP toolchain
### END INIT INFO

MODE=daemon
USER=www-data
HHVM=/usr/local/bin/hhvm
HHVM_CONFIG=/etc/hhvm/server.hdf
HHVM_OPTIONS="--config ${HHVM_CONFIG} --user ${USER} --mode ${MODE}"
prog=hhvm
pidfile=/run/hhvm/hhvm.pid
lockfile=/run/hhvm/hhvm.lock

# Source function library.
. /etc/rc.d/init.d/functions

if [ -f /etc/sysconfig/hhvm ]; then
        . /etc/sysconfig/hhvm
fi

test -x $HHVM || exit 1

start() {
    [ -d /run/hhvm ] || install -m 755 -o ${USER} -g root -d /run/hhvm
    echo -n $"Starting $prog: "
    daemon $HHVM $HHVM_OPTIONS
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && touch ${lockfile}

    #need to figure out how to start hack typechecker
    #cd /var/www/html
    #/usr/local/bin/hh_client
    return $RETVAL
}


stop() {
    echo -n $"Stopping $prog: "
    killproc -p ${pidfile} $HHVM
    RETVAL=$?
    echo
    [ $RETVAL = 0 ] && rm -f ${lockfile} ${pidfile}

    #need to figure out how to stop hack typechecker
	#pkill hh_server
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    reload|force-reload|restart|try-restart)
        stop
        sleep 2
        start
        ;;
    status)
        status -p ${pidfile} $httpd
        ;;

    *)
        echo "Usage: /etc/init.d/hhvm {start|stop|restart|status}"
        exit 2
esac

exit 0
