#!/bin/sh
#
#
# /etc/opt/csw/init.d/cswpuppetd
#
#   2014-08-06 Andy MyHR
#     * remove Solaris 10isms
#     * remove unused lines
#     * remove anything not needed for Sol 8/9
#
#   2011-05-06 Mark Phillips
#     * Check if we're on Solaris 10 before including the smf_include stuff
#
#   2011-03-06 Mark Phillips
#     * Added getprop - not used, yet
#
#   2009-10-21 Maciej Blizinski
#
#     * Introduced start/stop/reload as functions
#     * Distinguishing between reload and restart
#     * Made the script zone-friendly
#     * Supported custom pid file locations.
#
#   2009-11-23 Gary Law
#     * changed sbindir

#puppet_opts="--certname=intranet1.gpi.com"
#puppet_opts="--certname=intranet2.gpi.com"
puppet_opts=""
puppetd="/opt/csw/bin/puppet agent"
puppet_serv="--server=ral-pupmstr01.gpi.com"
pidfile=`$puppetd --configprint pidfile 2>/dev/null`

start_puppetd() {
    $puppetd $puppet_opts $puppet_serv 2>/dev/null
}

reload_puppetd() {
    if [ -r $pidfile ]; then
        kill -HUP `cat $pidfile`
    fi
}

stop_puppetd() {
    if [ -r $pidfile ]; then
        pid=`cat $pidfile`
        kill $pid
    fi
}

case "$1" in
    start)
        printf "Starting Puppet client services:"
        start_puppetd
        printf " puppetd"
        echo ""
        ;;
    stop)
        printf "Stopping Puppet client services:"
        stop_puppetd
        printf " puppetd"
        echo ""
        ;;
    restart)
        printf "Restarting Puppet client services:"
        stop_puppetd
        sleep 5
        start_puppetd
        printf " puppetd"
        echo ""
        ;;
    reload)
        printf "Reloading Puppet client services:"
        reload_puppetd
        printf " puppetd"
        echo ""
        ;;
    status)
        if [ -f $pidfile ]; then
            pid=`cat $pidfile`
            curpid=`pgrep -f '/opt/csw/bin/puppet'`
            if [ "$pid" -eq "$curpid" ]; then
                exit 0
            else
                exit 1
            fi
        else
            exit 1
        fi
        ;;
    *)
        echo "Usage: $0 { start | stop | restart | reload | status }"
        exit 1
            ;;
esac
exit 0

